### ISSUE TITLE
Dynamic Re-authentication failing when current token expires

### ISSUE THREAD

**Issue by OohDark30** [OohDark30/ecs-pulse#5]
Data collection routines failing to properly re-authenticate after original authentication token expires

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 87, in run
    ecs_collect_local_zone_bootstrap_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 913, in ecs_collect_local_zone_bootstrap_data
    replication_link_bootstrap_data = local_zone_bootstrap_data['_embedded']['_instances']
KeyError: '_embedded'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 84, in run
    ecs_collect_local_zone_replication_failure_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 750, in ecs_collect_local_zone_replication_failure_data
    local_zone_failed_failed_replication_link_data = ecsconnection.get_local_zone_replication_failure_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 184, in get_local_zone_replication_failure_data
    self.authentication.connect()
AttributeError: 'NoneType' object has no attribute 'connect'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 69, in run
    ecs_collect_capacity_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 119, in ecs_collect_capacity_data
    capacity_data = ecsconnection.get_capacity_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 267, in get_capacity_data
    self.authentication.connect()
AttributeError: 'NoneType' object has no attribute 'connect'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 72, in run
    ecs_collect_local_zone_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 225, in ecs_collect_local_zone_data
    local_zone_data = ecsconnection.get_local_zone_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 79, in get_local_zone_data
    headers = {'X-SDS-AUTH-TOKEN': "'{0}'".format(self.authentication.token), 'content-type': 'application/json'}
AttributeError: 'NoneType' object has no attribute 'token'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 75, in run
    ecs_collect_local_zone_node_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 343, in ecs_collect_local_zone_node_data
    local_zone_node_data = ecsconnection.get_local_zone_node_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 310, in get_local_zone_node_data
    self.authentication.connect()
AttributeError: 'NoneType' object has no attribute 'connect'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 78, in run
    ecs_collect_local_zone_disk_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 482, in ecs_collect_local_zone_disk_data
    local_zone_disk_data = ecsconnection.get_local_zone_disk_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 329, in get_local_zone_disk_data
    headers = {'X-SDS-AUTH-TOKEN': "'{0}'".format(self.authentication.token), 'content-type': 'application/json'}
AttributeError: 'NoneType' object has no attribute 'token'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 81, in run
    ecs_collect_local_zone_replication_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 614, in ecs_collect_local_zone_replication_data
    local_zone_replication_data = ecsconnection.get_local_zone_replication_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 120, in get_local_zone_replication_data
    headers = {'X-SDS-AUTH-TOKEN': "'{0}'".format(self.authentication.token), 'content-type': 'application/json'}
AttributeError: 'NoneType' object has no attribute 'token'

ECS_Data_Collection_Module__main__::Current directory is : /home/admin/ecs-pulse
ECS_Data_Collection_Module__main__::Configuration file path is: /home/admin/ecs-pulse/configuration/ecs_pulse_config.json
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 81, in run
    ecs_collect_local_zone_replication_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 646, in ecs_collect_local_zone_replication_data
    node_name = local_zone_replication_data['name']
KeyError: 'name'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 84, in run
    ecs_collect_local_zone_replication_failure_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 775, in ecs_collect_local_zone_replication_failure_data
    failed_replication_link_data = local_zone_failed_failed_replication_link_data['_embedded']['_instances']
KeyError: '_embedded'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 87, in run
    ecs_collect_local_zone_bootstrap_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 887, in ecs_collect_local_zone_bootstrap_data
    local_zone_bootstrap_data = ecsconnection.get_local_zone_bootstrap_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 225, in get_local_zone_bootstrap_data
    self.authentication.connect()
AttributeError: 'NoneType' object has no attribute 'connect'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 78, in run
    ecs_collect_local_zone_disk_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 482, in ecs_collect_local_zone_disk_data
    local_zone_disk_data = ecsconnection.get_local_zone_disk_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 329, in get_local_zone_disk_data
    headers = {'X-SDS-AUTH-TOKEN': "'{0}'".format(self.authentication.token), 'content-type': 'application/json'}
AttributeError: 'NoneType' object has no attribute 'token'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 75, in run
    ecs_collect_local_zone_node_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 343, in ecs_collect_local_zone_node_data
    local_zone_node_data = ecsconnection.get_local_zone_node_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 310, in get_local_zone_node_data
    self.authentication.connect()
AttributeError: 'NoneType' object has no attribute 'connect'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 72, in run
    ecs_collect_local_zone_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 225, in ecs_collect_local_zone_data
    local_zone_data = ecsconnection.get_local_zone_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 102, in get_local_zone_data
    self.authentication.connect()
AttributeError: 'NoneType' object has no attribute 'connect'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "ecs-pulse.py", line 69, in run
    ecs_collect_capacity_data(self.influxclient, self.logger, self.ecsmanagmentapi, self.pollinginterval)
  File "ecs-pulse.py", line 119, in ecs_collect_capacity_data
    capacity_data = ecsconnection.get_capacity_data()
  File "/home/admin/ecs-pulse/ecs/ecs.py", line 243, in get_capacity_data
    headers = {'X-SDS-AUTH-TOKEN': "'{0}'".format(self.authentication.token), 'content-type': 'application/json'}
AttributeError: 'NoneType' object has no attribute 'token'

ECS_Data_Collection_Module__main__::Current directory is : /home/admin/ecs-pulse
ECS_Data_Collection_Module__main__::Configuration file path is: /home/admin/ecs-pulse/configuration/ecs_pulse_config.json
`

**Comment by OohDark30** [comment]
Corrected and commited
